### PR TITLE
Updated light theme under 256 color terminals

### PR DESCRIPTION
**Pull request by martijnat**
Using screenshots is quite useful when showing what faces look like in
a pull requests however can take more time to do by hand than changing
the actual faces so I automated it.

### CODE REVIEW

**Comment by martijnat** [comment]
Also it turned out to be useful for https://github.com/greduan/emacs-theme-gruvbox/issues/87

**Comment by martijnat** [comment]
So I managed to make the terminal version of the the theme look better.

As it turns out your can use `M-x list-colors-display` when using a terminal to get a list of all valid color definitions.

Also when looking through the valid colors I found that there aren't many good light shades of brown which fit this theme, the [vim version](https://github.com/morhetz/gruvbox) of gruvbox actually defines theme in 256 colors however when using their definitions the theme look quite bad.

For reference here are some screenshots

light-hard (old)
oldgruvbox-light-hard

light hard (new)
newgruvbox-light-hard

Light-medium (old)
oldgruvbox-light-medium

light-medium (new)
newgruvbox-light-medium

Light-soft (old)
oldgruvbox-light-soft

light-soft (new)
newgruvbox-light-soft

**Comment by jasonm23** [comment]
I don't see problems with the old versions and the new light-soft variant is particularly off-model vis the 24bit version.

Can you explain each of the problems with the old versions so we can address them one by one.

**Comment by jasonm23** [comment]
Looking at #87 if that's the extent of the problems perhaps a better solution is that there is no difference between the hard med soft variants on terminal.

There is a lack of useful light background colors and subtlety on the 256 palette and if that's a serious problem for users they can simply migrate to 26 and use a true color terminal emulator shortly.

**Comment by martijnat** [comment]
> I don't see problems with the old versions

Its a minor annoyance; It has shades of gray, pink and yellow where I would like it to be shades of (light) brown.

> the new light-soft variant is particularly off-model vis the 24bit version.

It either a particularly harsh difference or making it the exact same as another version.

> Can you explain each of the problems with the old versions so we can address them one by one.

The light versions cause off-color faces for

- Background (I am not sure this can be fixed)
- Mode line (Active is grey, inactive is pink)
- Region (its grey)
- any other face that uses gruvbox-dark*

> perhaps a better solution is that there is no difference between the hard med soft variants on terminal.

I think that would a good comprimise, I suggest we stick with the light-hard version

> users they can simply migrate to 26 and use a true color terminal emulator shortly.

I just checked with konsole,gnome-terminal and xfce4-terminal. All off
them use the 256 color theme on emacs 256 despite being able to render
truecolor.

**Comment by jasonm23** [comment]
Sounds good

**Comment by jasonm23** [comment]
Pity about konsole, gnome and xfce4 terminals.

However I don't think those will be permanent problems.  Do you know which 24bit terminals do work with Emacs?

AFAIK there are at least 2 competing _standards_ for true color pseudo-ansi.

**Comment by jasonm23** [comment]
BTW - can you link me to some notes on Emacs 26 + true color.  I could only find links to the patch that did the rounds a few years ago.

**Comment by martijnat** [comment]
This is what (all) light versions now  look under 256-color terminals
updatedgruvbox-light-hard
Compared to their truecolor counterpart
referencegruvbox-light-hard

**Comment by martijnat** [comment]
> However I don't think those will be permanent problems.

I don't think it is a serious problem, however I don't think it will
automatically go away.

- Some popular terminals (xterm,urxvt) don't support truecolor
- Truecolor doesn't work with screen or tmux (tmux translates to 256 color, screen glitches out)

> Do you know which 24bit terminals do work with Emacs?

No, none of the emulator I tried seemed to work.

> AFAIK there are at least 2 competing standards for true color pseudo-ansi.

Only method I know of is [explained here](https://gist.github.com/XVilka/8346728)

> BTW - can you link me to some notes on Emacs 26 + true color.

Regarding truecolor on terminals [This is good
read](https://gist.github.com/XVilka/8346728), it is just a matter of
writing a specific sequence of characters to stdout.


Emacs's color mode can be changed by using the --color flag (altough I
am not sure wow it works), if that is not used then emacs tries to
guess what color mode the terminal supports. I know that setting $TERM
to xterm-256 "forces" emacs to use 256 colors and emacs will use 8
colors when $TERM is "xterm".

So either

- The current emacs master doesn't include the truecolor patch (no idea how to check that).

- Emacs doesn't corectly identify truecolor support in terminals. Perhaps this can be fixed by setting a variable.

**Comment by greduan** [comment]
> Truecolor doesn't work with screen or tmux (tmux translates to 256 color, screen glitches out)

I believe Tmux does have 256 color. Although maybe not on the latest release (not sure), it is on master.

https://github.com/kimat/tmux/commit/b2de2beadd64a1ed64ad162271a326a6437f6af0

With Neovim you can get true color even if using Tmux, so I believe the problem right now is Emacs.

**Comment by ninrod** [comment]
tmux does support true colors since tmux 2.2 I think. I use it everyday.

**Comment by jasonm23** [comment]
I'm a little bit confused, someone mentioned that there is official support for true color in Emacs 26 - is this correct, I cannot find mention of it.

**Comment by ninrod** [comment]
yes, it was mentioned by me. It is supported in emacs master (emacs 26). Its a patch by Rami Ylimaki. It's in the __[NEWS](https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS#L94-L98)__ file.

**Comment by jasonm23** [comment]
Thank you @ninrod

**Comment by martijnat** [comment]
I have figured out how to get truecolor support in terminal emacs. The process is detaild in the emacs FAQ (`C-h C-f`)

1. Create a file called `terminfo-24bit.src` with the following content.

```
# Use colon separators.
xterm-24bit|xterm with 24-bit direct color mode,
use=xterm-256color,
setb24=\E[48:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
setf24=\E[38:2:%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%dm,
# Use semicolon separators.
xterm-24bits|xterm with 24-bit direct color mode,
use=xterm-256color,
setb24=\E[48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
setf24=\E[38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%dm,
```

2. Run the command `tic -x -o ~/.terminfo terminfo-24bit.src`, this
   creates a folder with configuration telling programs how to encode
   color when when $TERM is set to `xterm-24bit` and `xterm-24bits`

3. Run emacs -nw with `$TERM` set to `xterm-24bit`, If you want to use it only once run emacs as `TERM=xterm-24bit emacs -nw`

This seems to work with gnome-terminal, xfce4-terminal.

st,konsole,cool-retro-term and urxvt fail.

Xterm approximates the colors quite nicely, which I will try to use as
a basis for the 256 color scheme.

> tmux does support true colors since tmux 2.2 I think. I use it everyday.

Apperantly it does, but not by default. You have to add

    set-option -ga terminal-overrides ",xterm-256color:Tc"

to your config file.

However it does not appear to work in conjunction with truecolor emacs
as described above.

**Comment by martijnat** [comment]
I used xterms approximation to find a nicer pallete

xtermgruvbox-light-hard

**Comment by ninrod** [comment]
@martijnat, the terminal has to have support to 24-bit colors. 

the whole chain has to have it, actually: terminal > tmux> application. 

See __[here](https://gist.github.com/XVilka/8346728)__ for a complete list.

**Comment by martijnat** [comment]
@ninrod 

- I can use emacs in truecolor without tmux
- I can use (some) truecolor programs in truecolor in tmux
- Trying to use 24bit color on emacs inside tmux fails

This is what happens:

cat

Left pane is a non-emacs program that uses truecolor (simple paint program I once wrote). Right bottom is emacs when run with `TERM=xterm-256color` and Topright is emacs when run with `TERM=xterm-24bit`

I am using tmux 2.5 and emacs 26

**Comment by ninrod** [comment]
hummm interesting. would you be able to produce a shot with emacs terminal 24bit with tmux, 24 bit without tmux and 256colors side by side?

**Comment by martijnat** [comment]
- tmux on top, without tmux on the bottom
- 256 colors on left, 24bit color on the right

grid

**Comment by ninrod** [comment]
yes, sounds like a bug in  the emacs  patch that introduced 24-bit support. Maybe ping Eli Zaretski and Rami Ylimaki. 

I don't believe this issue is related to tmux because vim8 works fine in tmux 2.5 with 24-bit color support.

**Comment by jasonm23** [comment]
Is this safe to merge @martijnat

**Pull request merged**
