### PR TITLE
Added colors for ediff mode

### PR DESCRIPTION
**Pull request by blairdrummond**
I added coloring for ediff-mode, I think it looks pretty good. Without this it's basically unreadable. Screenshot attached.

ediff_screenshot

### CODE REVIEW

**Comment by greduan** [comment]
I think it's a bit bright, but what do you think @jasonm23 ?

**Comment by jasonm23** [comment]
Yes too bright / gaudy for the theme

**Comment by blairdrummond** [comment]
That's fair. I was trying to get reasonable color contrasts, but I'll see if I can't find something a bit softer. I'll make some edits after exams and update this.

**Comment by jasonm23** [comment]
I will have a look 


Sent from my iPhone

**Comment by blairdrummond** [comment]
I tried out something else, but I had to create new colors. Let me know what you think. If you like it, what should I do about the new colors? Give them names? Or just leave them as anonymous hex colors?

screenshot_2016-04-23_12-42-28


screenshot_2016-04-23_13-06-07

**Comment by greduan** [comment]
I think it looks good but deviates from the original colors a bit much for my liking... In any case, I think the coloro palette is the same but I like how the second image looks, way better than the first, again I think they're the same palette just different contents, correct?

Perhaps take a look at @d125q's Gruvbox dark version for reference colors?: https://github.com/d125q/gruvbox-dark-emacs

From what I understand its colors are darker than ours, while still being Gruvbox colors. IIRC the reason he made that theme is because ours uses the bright colors of the theme while his uses the darker, more normal, colors. This is just from memory though. If you're interested take a look at https://github.com/greduan/emacs-theme-gruvbox/issues/32

**Comment by jasonm23** [comment]
I think this will need to be closed.  I like the dark colors but it doesn't fit with the Gruvbox palette.

Once we've integrated the light and dark themes it might be worth trying this again.

**Pull request closed without merging**
