### PR TITLE
Improve contrast of diff-refine for dark-* and light-* themes

### PR DESCRIPTION
**Pull request by ywwry66**
In my previous PR #213, the highlighting is only optimized for `gruvbox-theme`. For `gruvbox-dark-*-theme` and `gruvbox-light-*-theme` themes, the result was bad (see the screenshot below) because of low contrast between, say `gruvbox-bright_green` and `gruvbox-faded_green`.
Screenshot 2024-05-14 at 11 22 13 PM

This PR attempts to address the issue. Attached are the screenshots for `gruvbox-theme`, `gruvbox-dark-medium-theme` and `gruvbox-light-medium-theme` after the changes.
Screenshot 2024-05-14 at 11 01 16 PM
Screenshot 2024-05-14 at 11 00 08 PM
Screenshot 2024-05-14 at 10 59 23 PM

### CODE REVIEW

**Comment by jasonm23** [comment]
Good, thank you for updating the variants.

You can comment here when/if you think the piece of work is suitable as a new tagged release.

**Comment by jasonm23** [comment]
Merged, available as head release via MELPA on their next build cycle.

**Comment by ywwry66** [comment]
Thanks for the quick merge. I will use it a little longer to ensure it is suitable for stable release. In the meantime, the community might provide feedback.

**Comment by ywwry66** [comment]
👋 Just want to report back that the change has worked pretty well for my daily usage of the past few months.

**Comment by jasonm23** [comment]
New stable release dropped.

**Pull request merged**
