### PR TITLE
Add faces for git-gutter.

### PR DESCRIPTION
**Pull request by kostafey**

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you for this too.  Please add screenshots showing gitgutter add/remove/change for each of the gruvbox theme styles.

**Comment by jasonm23** [comment]
(screenshots should just be added to this pull request conversation)

**Comment by kostafey** [comment]
gruvbox-dark-soft
gitter-dark
gruvbox-light-soft
gitter-light

**Comment by jasonm23** [comment]
Take a look at how gitgutter theme support was added to emacs darktooth.

Setting these symbols with background color is more pleasant to my eyes.

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/emacs-theme-darktooth

**Comment by kostafey** [comment]
Do you mean we should use faded colors?

**Comment by kostafey** [comment]
ping. Actual (faded) colors screenshot:
gitter-dark-faded
gitter-light-faded

**Comment by jasonm23** [comment]
Sorry, that's not what I meant.

I'm asking you to set the color as background instead of foreground.  

The foreground should be set to something neutral

**Comment by kostafey** [comment]
But background with neutral colored +/- signs looks ugly. Why not use background color only like in modern IDEs?
gitter-dark-back
gitter-light-back

**Comment by jasonm23** [comment]
Not what I had in mind, but looks good. 👍

**Pull request merged**
