### PR TITLE
Add faces for tabbar.

### PR DESCRIPTION
**Pull request by kostafey**

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you for contributing.

Please include a screenshot of the different gruvbox dark and light theme styles showing the tab bar.

**Comment by jasonm23** [comment]
(attach screenshots to this conversation)

**Comment by kostafey** [comment]
Here `gruvbox-light-soft-theme.el` buffer is actual buffer (yellow) and `gruvbox-dark-soft-theme.el` buffer (green) is midified but not saved.
gruvbox-dark-soft:
tabbar
gruvbox-light-soft:
tabbar-light

**Comment by jasonm23** [comment]
Thanks LGTM

**Pull request merged**
