### PR TITLE
alternative ediff faces that retain syntax highlighting

### PR DESCRIPTION
**Pull request by ssnnoo**
Currently ediff faces use gruvbox colours but the prices for that is that syntax highlighting is lost (without specifying any faces, ediff readability was poor).

Keeping syntax highlighting in the diff region is only possible if colours are used for diffs that are sufficiently different from the colours used for syntax highlighing.

These ediff faces would retain syntax highlighting while still provide sufficient readability ; They do not use gruvbox colours, but arguably this is less essential than userbility - given that only a fraction of time is spend diffing changes.

New faces:
new_dark
new_light

for comparison, current faces:
current_dark
current_light

Please let me know what you thing about this!

### CODE REVIEW

**Comment by jasonm23** [comment]
Agree, looks significantly better than current.

(btw, usability)

I'm happy to approve this change. 

@greduan any comment?

**Comment by ssnnoo** [comment]
Let's merge it then? It is easy to remove should anyone complain :-)

**Comment by jasonm23** [comment]
Sure seems like enough pause if @greduan had an issue with this.

The only consideration I could imagine to be concerned about, is that gruvbox is a cross platform theme.  However, I am fairly sure it's emacs variant is already divergent enough for that to be a non issue at this point.

**Comment by ssnnoo** [comment]
Very good point. I don't use vim, only found this screenshot [vimdiff](https://github.com/morhetz/gruvbox/issues/40#issuecomment-138878017) which suggest that syntax highlighting is not preserved; I don't know if this is a limitation of vimdiff or a theme choice though. If it is a limitation, the option would be to not make use of some emacs features for consistency reasons, or diverge for usability reasons.

What is currently not working that well with the dark theme are diffs (e.g. diff-buffers) - they are a bit to difficult to read - and there would be the option to make them consistent with these ediff faces. I am happy to do it if you, @jasonm23 @greduan  are fine with this approach.

current colours for diffs, dark and light theme:

diff_dark
diff_light

and the new ediff faces for comparison (dark):
ediff_dark

**Comment by jasonm23** [comment]
I think if there are complaints we'll deal with it if they arise

**Pull request merged**
