### PR TITLE
Add support for org-mode

### PR DESCRIPTION
**Pull request by atheriel**
This is a fairly complete set of faces for `org-mode`, based on the `org-faces.el` file and a cursory look at what other themes do or do not modify.

I've also added support for the common extension `org-habit`, and added support for two of the built-in faces, `shadow` and `link` (both of which are used by `org-mode` but also by many other packages).

### CODE REVIEW

**Comment by jasonm23** [comment]
thank you 

Please attach a screen grab demonstrating the theme changes

**Comment by atheriel** [comment]
OK, I'll put something together.

**Comment by jasonm23** [comment]
Thank you, thank you!

**Comment by greduan** [comment]
This probably solves https://github.com/greduan/emacs-theme-gruvbox/issues/25

**Comment by atheriel** [comment]
Before: default colours, plus org-mode's default inheritance of font-lock

screen shot 2016-09-06 at 9 38 55 pm

After: more consistent, semantically correct when possible

screen shot 2016-09-06 at 9 39 22 pm

**Comment by jasonm23** [comment]
LGTM

**Comment by greduan** [comment]
LGTM, very nice. 👍 

Feel free to merge it @jasonm23.

**Pull request merged**
