### PR TITLE
Updated colors to match vim theme

### PR DESCRIPTION
**Pull request by martijnat**
- Removed neutral-* color variants, leaving only faded-* and bright-*
- Changed all faced using neutral variants to use bright variants
- Changed faded-* color variants to match vim versions
- Updated screenshots

gruvbox-dark-hard-screenshot
gruvbox-dark-medium-screenshot
gruvbox-dark-soft-screenshot
gruvbox-light-hard-screenshot
gruvbox-light-medium-screenshot
gruvbox-light-soft-screenshot

### CODE REVIEW

**Comment by jasonm23** [comment]
Side by side with Vim?

**Comment by BerberBerthold** [comment]
Thanks!

At first I was irritated when I saw you removed the "normal" labeled colors. But then I took a look at the original vim gruvbox theme, and there, the "normal" labeled colors are not used either. I don't know how exactly vim themeing works, but I can't find it in the source code except for the part that checks if neovim is used. That is weird. So the original's README is misleading I guess...

In the gruvbox .Xresources, which looks like it's the same as the neovim (nvim) configuration, the "neutral" colors are used though. I think it is very confusing. Apparently a lot of stuff is not consistent, which is annoying, since I want my terminal to look like my Emacs.

But at least the colors are now like the original.

**Comment by martijnat** [comment]
I am not in favour of merging this quickly because I changed a lot of
code and there is a good chance I made a mistake somewhere. I will be
using this branch personally for a while to see if I can spot any
mistake.

I am however in favour of merging this eventually.

- I think the removal of the neutral faces is a good thing.
- I think it the new faded colors look better.
- This update would mean the theme can be consistent across applications.
- The appearance of the most prominent faces are not changed at all.
  In fact it is quite hard to spot the difference unless you are
  comparing two applications side by side.

> Side by side with Vim?

I am not al that familiar with vim.

- I can only get the medium contrast light version working.
- I do not know where vim used the faded colors.

It matches with the .Xresources version and that is good enough for
me.

**Comment by BerberBerthold** [comment]
Hm ok I took a look at it again. Now I think I understand what you did, though. I also took a look at the official .Xresources again as well.

Going by the original terminology...
- Vim dark has bright only (unless nvim??)
- Vim light has faded only (unless nvim??)
- .Xresources dark has neutral and bright
- .Xresources light has neutral and faded

- This branch dark has neutral and bright, but neutral was renamed to faded
- This branch light has neutral and faded, but neutral was renamed to faded AND faded was renamed to bright

Now your branch really does match .Xresources (at least the colors that are present), but the terminology is all messed up.

**Comment by martijnat** [comment]
@BerberBerthold 

This is the dark color pallette I work off

dark

The faded colors are the first row, the bright colors are the second row. The faded colors contrast a little with the background color, the bright colors contrast a lot with the background color.


This is the light pallette  I work off.

light

Even though the second row is darker than the first row, it provides the "role" the bright colors have in the dark theme and are named such.

If we compare that to the ~[.Xresources variant](https://github.com/morhetz/gruvbox-contrib/tree/master/xresources), what we call faded-red, is called darkred in the .Xresources file and what we call bright-red is called red in the .xresources file. (Even tought darkred is lighted than red in the light version).

**Comment by BerberBerthold** [comment]
I see, functionally it makes sense.

Maybe we should rename it to "darkred" and "red", just like in the .Xresources file, in a functional sense.

I think the actual color #FB4934 should be consistently called "gruvbox-bright-red", #CC241D "gruvbox-neutral-red" and #9D0006 "gruvbox-faded-red". And so on...

I believe that would be less confusing.

Sorry if I am being nitpicky ^^

**Comment by martijnat** [comment]
So I have been using this branch for over a week now and I think we should merge it. The "bright" variants are used much more often than the faded variant so their effect on the overall theme is a bit hard to judge.

This is a comparison of the color changes in the dark versions of the theme.

colors_dark

The bright colors are unchanged. The new faded colors are a bit lighter. This makes them easier to see against the background. I do not think they are to hard to distinguish from their bright counterparts and I think they fit better than their old versions.

The light theme on the other hand has a more noticeable change.

colors_light

Due to my mistake, in the old version the neutral- and bright- variants of each color was taken from the vim light theme, yet the faded-* variant were simply copied from the dark version. I think the old versions colors were a bit too bright compared to the background, especially on the light-hard version.

I think we can make this change even if it changed the overall look of the theme slightly. Lately we already updated common faces https://github.com/greduan/emacs-theme-gruvbox/pull/78 https://github.com/greduan/emacs-theme-gruvbox/pull/82 https://github.com/greduan/emacs-theme-gruvbox/pull/81 https://github.com/greduan/emacs-theme-gruvbox/pull/90 without any complaints and the differences in the light theme are actually unintended.

I will leave this pull request open until Monday. If @greduan or @jasonm23 have any complaints I will try to address them. If not I will merge this pull request.

**Comment by greduan** [comment]
I have no problem, but instead of "merge by default" please wait for Jason's approval. Sometimes we don't check GitHub every day :)

**Comment by BerberBerthold** [comment]
Again, might I add, I think calling them "bright" and "faded" is confusing. I would call them "major" and "minor", or "[color]" and "alt [color]". Also because the colors are consistently named by their exact shade and not by their function in the original.

Example:

- #FB4934 "gruvbox-bright-red"
- #CC241D "gruvbox-neutral-red"
- #9D0006 "gruvbox-faded-red"

are the names in the original.

But then specifically for the dark theme, I would suggest

- "major red" refers to #FB4934 "gruvbox-bright-red"
- "minor red" refers to #CC241D "gruvbox-neutral-red"

and for the light theme

- "major red" refers to #9D0006 "gruvbox-faded-red"
- "minor red" refers to #CC241D "gruvbox-neutral-red"

This way it is more consistent with the original, and also, your way, the darker color being called "bright" also doesn't feel right.

**Comment by jasonm23** [comment]
Sorry to be a party pooper guys, with the same number of interested parties, I'm not convinced that existing users are wanting this change.

At this point I'm considering closing the PR. This theme doesn't belong to us, we are just contributors and maintenance crew.  We don't own it, we simply steward it.

If we can look at this situation at the end of next week with some user feedback, I will be happy to move on this.

@berberberthold re: bright vs major / minor, regarding vim Gruvbox alignment.  I think it takes us further away from that goal.

**Comment by BerberBerthold** [comment]
I don't get how it goes away from the goal of having it align with gruvbox. The way I suggested it, the colors would still have the same names as vim, but the "faded red" would ALWAYS be #9D006, which is exactly like the vim version handles the naming of the colors. And the "major/minor" would just refer to its use. Maybe a better name would be red 1 and red 9, I dunno, but whatever, I have mentioned everything I wanted to mention.

I will create my own version of emacs gruvbox I guess. Or use this fork. I like this fork very much!

I wonder what the user feedback would be...

**Comment by jasonm23** [comment]
For this PR, consider major minor naming idea off topic. Of course It's ok to open it up as another issue if you like.

Re: the palette change.

@berberberthold, there are hundreds of (at least) active users of this theme and changing core palette colors would probably be an annoyance.  I'd like to make sure that's noted as the reason why I'm not merging at this time.

**Comment by martijnat** [comment]
@jasonm23

In this PR, the default theme, `gruvbox-theme` is actually unchanged.
This PR should only affect those that have setup a variant. Users that
have been using this theme for years should not notice anything
different.

@BerberBerthold

How we name the color variants is only important for
maintaining the theme. As long as it is internally consistent I see no
reason to spend any effort change it.

**Comment by jasonm23** [comment]
Thanks for clarifying @martijnat. If we're not modifying the default palette, there shouldn't be any issue with merging.

I'll look closely at this today (6am now) and merge unless I notice any problems.

**Comment by jasonm23** [comment]
Ok.  LGTM. :+1:

**Pull request merged**
