### PR TITLE
when gruvbox-bold-constructs is t, make org headlines bold

### PR DESCRIPTION
**Pull request by skyler544**
This PR expands the effect of the `gruvbox-bold-constructs` user option to apply to Org headlines.

It may make more sense to put this behind a new user option (`gruvbox-bold-org-headlines` for instance) instead of reusing the existing one, if the majority of users do not expect this option to affect Org headlines.

### CODE REVIEW

**Comment by jasonm23** [comment]
Please add screen shots highlighting the PR change(s)

Be sure to show all variants 

Thank you 🙏

**Comment by skyler544** [comment]
Sure, here are some screenshots.

gruvbox-dark-hard
gruvbox-dark-medium
gruvbox-dark-soft
gruvbox-light-hard
gruvbox-light-medium
gruvbox-light-soft

**Comment by jasonm23** [comment]
Thank you, please edit the comment to show before/after.

**Comment by jasonm23** [comment]
Looks great, thank you.

Merging.

**Pull request merged**
