### PR TITLE
Add support for powerline

### PR DESCRIPTION
**Pull request by peteralm80**

### CODE REVIEW

**Comment by greduan** [comment]
Hi @peteralm80 , thanks for your PR 🙂 

Could you provide screenshots of what the result looks like? If you can provide before pics that'd also be great (just for comparing 🙂 ).

**Comment by martijnat** [comment]
This pull request still has some issues.

For comparison is what the powerline modeline (default theme) looks like with the current gruvbox theme.

1525084827-window
1525084893-window

For the dark versions of the theme the powerline mode line look just fine but the colors are wrong for the light versions.

Now compare this this to what the mode line looks like after this patch:

1525085084-window
1525085099-window

I don't know why but the colors of the unicode triangle separators is now wrong.

**Comment by peteralm80** [comment]
@martijnat You need to call powerline-reset after changing the theme, the separators are cached as images and won't automatically be regenerated when you switch themes.

**Comment by martijnat** [comment]
@peteralm80 , yup that fixes it.

1525089132-window
1525089149-window

**Pull request merged**
