### PR TITLE
Maintenance for #65

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by jasonm23** [comment]
@martijnat - I'm adding the maintenance commits for #65

**Comment by jasonm23** [comment]
@martijnat - please review / comment and I'll merge everything in.

**Comment by martijnat** [comment]
Looks all good to me.

I was going to ask if you wanted to display screenshots of all the theme variants but I see you added that change while I was typing my comment.

**Comment by jasonm23** [comment]
Note: If we get complaints from existing users they can be directed to the MELPA stable release (until we place a git TAG on this release)

**Comment by jasonm23** [comment]
@martijnat I may not be awake when MELPA builds again, so please comment here when you install the update from MELPA edge, and note if you experience any problems.

**Comment by jasonm23** [comment]
Ref: MELPA recipe https://github.com/melpa/melpa/blob/master/recipes/gruvbox-theme

**Comment by jasonm23** [comment]
@martijnat - once again, thank you for getting this done.  Great work!

👍

**Pull request merged**
