### PR TITLE
Added missed faces for flyspell and customize

### PR DESCRIPTION
**Pull request by martijnat**
New look:

new-gruvbox-dark-hard
new-gruvbox-dark-medium
new-gruvbox-dark-soft
new-gruvbox-light-hard
new-gruvbox-light-medium
new-gruvbox-light-soft

Old look for reference

old-gruvbox-dark-hard
old-gruvbox-dark-medium
old-gruvbox-dark-soft
old-gruvbox-light-hard
old-gruvbox-light-medium
old-gruvbox-light-soft

### CODE REVIEW

**Comment by greduan** [comment]
For the flyspell buffer, looks good. As for the error indicators, personally I prefer the squiggly underline, because it's an addition to whatever syntax is already there, instead of changing/overriding it. That's my two cents.

**Comment by martijnat** [comment]
I personally dislike the squiggly line because they look ugly, are hard to spot and telling the difference between an orange squiggly underline and red squiggly underline is difficult.

What do you think of the following?

underline-gruvbox-dark-hard
underline-gruvbox-dark-medium
underline-gruvbox-dark-soft
underline-gruvbox-light-hard
underline-gruvbox-light-medium
underline-gruvbox-light-soft

**Comment by martijnat** [comment]
I personally dislike the squiggly line because they look ugly, are hard to spot and telling the difference between an orange squiggly underline and red squiggly underline is difficult.

What do you think of the following?

underline-gruvbox-dark-hard
underline-gruvbox-dark-medium
underline-gruvbox-dark-soft
underline-gruvbox-light-hard
underline-gruvbox-light-medium
underline-gruvbox-light-soft

Also colored underlines (or squiggly lines for that matter) are not possible in terminal so in a terminal it looks like this

terminal

**Comment by greduan** [comment]
That looks much nicer yes. Maybe the bolding is not necessary but that's just being picky at that point. :)

**Comment by jasonm23** [comment]
LGTM :+1:

**Pull request merged**
