### PR TITLE
Preliminary support for the light variant

### PR DESCRIPTION
**Pull request by atheriel**
Note that the diff for this PR is going to look excessive, but that's because of the refactoring. Check out the individual commits for a more incremental narrative.

I took the same approach that is used in e.g. the Solarized theme for providing more than one variant.

The theme in this PR should be almost 100% identical to the current dark theme, although I'd like someone else to check it out locally if possible.

_Update:_

This PR does three distinct things. The first is refactoring the current use of `custom-set-theme` into a macro that takes a `variant` argument (the first commit). The second is changing the current colours to reflect `fg` and `bg` instead of `light` and `dark`, which allows using the `variant` to set these colours directly instead (second commit). The third change (which will break EVERY configuration, btw) is creating two new theme files: `gruvbox-dark` and `gruvbox-light` (third commit).

To get the same behaviour as the master branch, you'll need to replace the loading of  the `gruvbox` theme with loading of the `gruvbox-dark` theme instead.

### CODE REVIEW

**Comment by idoo** [comment]
@greduan 👻 did you saw this MR ?)

**Comment by greduan** [comment]
@idoo 
Ah I missed it, thanks for notifying me. :slightly_smiling_face: 

@atheriel 
So if I understand right this is to provide the dark and light versions of the theme. Nice!

Sadly I can't test it locally right now as I haven't used Emacs in a couple months and this is a new computer.

Could you provide screenshots of the dark and light themes? Would love to see it in action. :wink:

**Comment by atheriel** [comment]
@greduan The dark theme should be identical to the current `master` branch. The light theme just reverses the dark and light colours at the moment, so it looks like this:

light theme

I've just rebased this branch heavily to get it consistent with master. I'll add some more detail to the PR description to explain the changes more carefully.

**Comment by jasonm23** [comment]
This work will be re-done (somehow) after the autothemer update.

**Comment by jasonm23** [comment]
For now I'll need to close the PR.

**Pull request closed without merging**
