### PR TITLE
Make vertical border less harsh on the eyes

### PR DESCRIPTION
**Pull request by Dominionized**
Before :
screen shot 2016-05-12 at 12 10 18 pm

After :
screen shot 2016-05-12 at 12 10 43 pm

### CODE REVIEW

**Comment by greduan** [comment]
That's fine, but I would still like it to stand out, otherwise there's no point in there being a border. You think you could give it a slightly lighter tone? Could be the same one as the modeline selection.

**Comment by jasonm23** [comment]
Agreed less harsh is a good idea, but what I see here is polar opposite to what has been working for Gruvbox for a long time.

Dim the line color by about 30% and I'd give it :+1:

**Comment by Dominionized** [comment]
Updated to match the modeline

**Comment by greduan** [comment]
Think you could post a pic of that?

**Comment by Dominionized** [comment]
Here you go : 
gruvbox new color

**Comment by jasonm23** [comment]
LGTM :+1:

**Comment by Dominionized** [comment]
Cool, thanks ! By the way, you guys should absolutely merge with https://github.com/d125q/gruvbox-dark-emacs. I've been actually using the latter for a few days, and it's more complete.

**Comment by jasonm23** [comment]
It was suggested, the author has made no reply so far.  That was months ago.

**Comment by greduan** [comment]
LGTM as well. 👍

**Pull request merged**
