### PR TITLE
Light version / additional faces

### PR DESCRIPTION
**Pull request by martijnat**
1. Updated terminal faces
2. Added faces for mu4e
3. Added customize group
4. Added light version

Note: Rather than the theme "gruvbox" you now have to load either "gruvbox-dark" or gruvbox-light"

### CODE REVIEW

**Comment by jasonm23** [comment]
Nice work @martijnat please attach a few screenshots of light theme (as comments) in here.

**Comment by jasonm23** [comment]
Please alias gruvbox to gruvbox-dark

**Comment by martijnat** [comment]
Here are screenshots for all the theme variations
gruvbox_dark_hard
gruvbox_dark_medium
gruvbox_dark_soft
gruvbox_light_hard
gruvbox_light_medium
gruvbox_light_soft

I have tried to figure out how to alias gruvbox to gruvbox dark, but could not figure it out.

 Right now I just copied all of gruvbox-dark to gruvbox. It is not the cleanest solution but it works as long as we don't update one version but not the other.

**Comment by greduan** [comment]
Damn nice work @martijnat :smile:

For the alias of gruvbox-dark to gruvbox, instead of copying the file could a file alias be used? Or is it possible to re-export the contents of another file somehow? (Not an elisp expert.)

**Comment by martijnat** [comment]
Aliases seems to work for symbols however. I am not sure what a "file alias" is but if you mean a symbolic link/shortcut to another file, then no: the theme name has to be specified in the files content.

The clean way to deal with these versions is to use macros. However since defining a theme is itself a macro you are dealing with nested macro which can lead to complicated quoting/unquoting. I tried doing that with my own theme but eventually dropped the idea because it was too complex. I will give it a try tonight.

If this can be rewritten I would like to propose the following

1. Get rid of the gruvbox-contrast variable
2. Form macros in a single file generate the following themes

- gruvbox-dark-soft
- gruvbox-dark-medium
- gruvbox-dark-hard
- gruvbox-light-soft
- gruvbox-light-medium
- gruvbox-light-hard
- gruvbox (which would be exactly like gruvbox-dark-medium to not break peoples configs)

Lastly, what is up with the specific pallete for 256 color terminal? All 256-color terminals I have used seem to approximate truecolor defininitions with 256 colors pallets quite fine.

**Comment by martijnat** [comment]
In the latest version I created a simple macro that holds all the face definitions, now each variant only has to only define its palette.

**Comment by martijnat** [comment]
The latest version now defines the following themes

-    gruvbox-dark-soft
-    gruvbox-dark-medium
-    gruvbox-dark-hard
-    gruvbox-light-soft
-    gruvbox-light-medium
-    gruvbox-light-hard
-    gruvbox (which would be exactly like gruvbox-dark-medium to not break peoples configs)

I also removed the customizable variable gruvbox-contrast. This should not break any existing configs.

**Comment by jasonm23** [comment]
Nice work, and a good play to extend the autothemer macro as gruvbox-theme.  Certainly addresses my concerns on maintainability.

I will need the README / [palette](https://github.com/greduan/emacs-theme-gruvbox/tree/master/palette) updated to reflect the update.

I will have a look at doing that today.

**Comment by jasonm23** [comment]
Just a note on the 256 terminal palette. Color mapping from 24bit often works, but not always.  The explicit palette is there to address those issues.

**Comment by jasonm23** [comment]
Migrated to #66 - please rebase on the `dark-fixes` branch if you would like to make additional commits.

**Comment by jasonm23** [comment]
(Closing this pull request see #66)

**Pull request closed without merging**
