### PR TITLE
Let diff-header use gruvbox background colors

### PR DESCRIPTION
**Pull request by theothornhill**
Adds some background colors to diff-header in diff-mode

### CODE REVIEW

**Comment by theothornhill** [comment]
Added some more colors so that the diff output looks a bit more like magits

**Comment by jasonm23** [comment]
Please add a before and after screen shot for this PR 

Thank you

**Comment by russell** [comment]
I tried this

## before
Screenshot from 2020-09-11 10-25-53

## after
Screenshot from 2020-09-11 10-28-31


this is what my magit status buffer looks like for context

Screenshot from 2020-09-11 10-42-09

I think that making the background of the context lines different in this way make it more difficult for me to read.  It seems to be trying to bring out the context lines not the change.

I did try flipping the background colours, it's possibly better? but it's pretty subjective. @theothornhill what do you think?

Screenshot from 2020-09-11 10-34-27

I have parked my change here https://github.com/russell/emacs-theme-gruvbox/commit/149644e9e72c95605e7200b17a278fdcff3fcacc

**Comment by theothornhill** [comment]
> I did try flipping the background colours, it's possibly better? but it's pretty subjective. @theothornhill what do you think?

I completely forgot about this, thanks for pinging 👍 

I don't think it looked like that in dark mode, but I don't remember. 

I don't use this theme anymore - feel free to pick it up if you want!

**Comment by ssnnoo** [comment]
I think it is either possible to retain syntax highlighting in the diff and use some non-gruvbox colour for highlighting the changes or sacrifice syntax highlighting. Just submitted this pull request for [ediff faces](https://github.com/greduan/emacs-theme-gruvbox/pull/175#issue-547057335) ; these colours could also be used here. important to test with light and dark theme.

**Comment by jasonm23** [comment]
Looks good.  Thank you.

**Pull request merged**
