### PR TITLE
Sync colors with gruvbox.vim

### PR DESCRIPTION
**Pull request by idoo**

### CODE REVIEW

**Comment by greduan** [comment]
@idoo thank you for your PR! Much appreciated. :smile:

Do you have available a before and after screenshots of the theme? Just so it's on record in a visual manner and also because I've no access to Emacs right now like to test it :stuck_out_tongue_winking_eye:

**Comment by idoo** [comment]
@greduan  as I can see it's minor changes, so changed only tones of color
new
old

**Comment by greduan** [comment]
@jasonm23 what should be done so these changes don't interfere with the refactor you guys are doing?

**Comment by jasonm23** [comment]
@greduan we can accept color changes to the palette.  There's not too much we can do to avoid additional manual update work though.

**Comment by jasonm23** [comment]
Don't worry though I have a xterm number to hex converter in my Emacs, that's the only bit thats manually painful usually.

in the update branch we're converting all xterm color numbers to hex (because Emacs throws all those silly error messages)

**Pull request merged**
