### PR TITLE
Add ansi-color block

### PR DESCRIPTION
**Pull request by BrachystochroneSD**
# The problem: 
Ansi colors wasn't updated by the theme. This impacted `*shell*` colors and other mode that used `comint-mode` (f.ex. `godot-mode`). 

# The Cause:
Current version of Gruvbox theme only change the now obsolete variable `ansi-color-names-vector`

# The Solution 

from help page for ansi-color-name-vector:

> This variable is obsolete.  To customize the display of colors used by
> ansi-color, change ’ansi-color-COLOR’, e.g. ‘ansi-color-red’.  To
> customize the actual faces used (e.g. to temporarily display SGR
> control sequences differently), use ‘ansi-color-normal-colors-vector’.

I only put a block on gruvbox.el that set all colors used by shell and comint (and potentialy everything that use built-in ansi-colors). Not sure if the background is needed for each of them. To be fair, I used the `term` block as an inspiration, and it seems to be enough

image

### CODE REVIEW

**Comment by BrachystochroneSD** [comment]
For your information, this was the situation before adding the block:

image

**Comment by jasonm23** [comment]
Thanks for the update.

Can we get these images  without whatever it is blurring the image.

**Comment by BrachystochroneSD** [comment]
Sure, 

## Before
image

## After:
image

**Comment by jasonm23** [comment]
Thank you.

**Pull request merged**
