### PR TITLE
Added latex verbatim face

### PR DESCRIPTION
**Pull request by martijnat**
I found a face I missed in https://github.com/greduan/emacs-theme-gruvbox/pull/97

old look:

verbatim-old-gruvbox-dark-hard
verbatim-old-gruvbox-dark-medium
verbatim-old-gruvbox-dark-soft
verbatim-old-gruvbox-light-hard
verbatim-old-gruvbox-light-medium
verbatim-old-gruvbox-light-soft

new look:

verbatim-new-gruvbox-dark-hard
verbatim-new-gruvbox-dark-medium
verbatim-new-gruvbox-dark-soft
verbatim-new-gruvbox-light-hard
verbatim-new-gruvbox-light-medium
verbatim-new-gruvbox-light-soft

### CODE REVIEW

**Comment by greduan** [comment]
LGTM

**Comment by jasonm23** [comment]
Looks good to me

Will need a semver patch number bump.

**Comment by martijnat** [comment]
@jasonm23 Changing the version number so frequently seems needlessly complex to me.

**Comment by jasonm23** [comment]
Sorry about that.  We have slipped on patching it while you've been so active and it should have been bumped every time.

The version is a reflection of change and not a marketing tool.  Ultimately public facing code should be versioned as regularly as it's changed.  This way users can know that a version of the software is a clear indication that they are using a different piece of work than another.

Most users will be getting their Emacs packages via MELPA, where each build of the package will get a timestamp version number.

It's only fair to other users who get their packages via other means, that version numbers have real meaning and values.

**Comment by jasonm23** [comment]
BTW if you feel that a PR isn't yet fully finished let's start using a label to indicate this.

E.g. DO NOT MERGE or WIP, etc.

I can understand that bumping version when you don't feel that a slice of work is completed, could feel wrong.

**Comment by jasonm23** [comment]
> The version is a reflection of change and not a marketing tool. 

That said, they are the only way to concisely communicate that changes are made/available.

**Comment by jasonm23** [comment]
Ah! So I just saw your version bump commit.  

This should be a patch change, not a point change.

Have a look at http://semver.org 

In essence it's broken down like this:

**Comment by greduan** [comment]
> This should be a patch change, not a point (or Minor) change.

Just a suggestion that I implement in my own work, maybe it's less trouble to assume `patch` is unexistent. That is not to say that it should be `v1.2` instead of `v1.2.0`, I mean that just always bump `minor` and ignore `patch`, always staying at `0`.

Reason for this suggestion was a good argument I saw (that I cannot for the life of me find) arguing that there will always be an argument on whether a new version should be `minor` or `patch`. To avoid that argument the solution proposed was to always bump `minor` and that's it.

That's been my preference for a long time now, feel free to use `patch` if you feel more comfortable. But just to say, if there is disagreement on whether something is `minor` or `patch`, it's always a safe solution to just bump `minor`.

**Comment by martijnat** [comment]
@greduan 

> The version is a reflection of change and not a marketing tool. Ultimately public facing code should be versioned as regularly as it's changed. This way users can know that a version of the software is a clear indication that they are using a different piece of work than another.

Makes sense

> This should be a patch change, not a point (or Minor) change.

I added a new face. As far as I can tell that is adding functionality without breaking backwards compatibility. To me changing the minor version seems more logical.

**Comment by jasonm23** [comment]
When we add support for a new mode(s) consider that a good case for a minor.  When modifying support for an existing mode we already support, consider that a patch.

Major version increment will only happen when there is a significant change to the implementation of the theme.  Although even when we switched to Autothemer and added light versions we didn't do that.

The inconsistency of versioning isn't something that I think should continue, and as there are a constant stream of changes in this theme, it's a good idea to keep minor version bumps to a minimum.

**Comment by martijnat** [comment]
Now the version goes from 1.21.0 to 1.21.1 (instead of 1.22.0)

**Comment by jasonm23** [comment]
Thank you @martijnat

**Pull request merged**
