### PR TITLE
Added faces for ido-mode

### PR DESCRIPTION
**Pull request by martijnat**
Before:

old-ido-dark
old-ido-dark-match
old-ido-light
old-ido-light-match

After:

new-ido-dark
new-ido-dark-match
new-ido-light
new-ido-light-match

### CODE REVIEW

**Comment by greduan** [comment]
Thanks. 🙂 Question, could you whenever you add new supports, add them to the README? Best way to keep it up to date I think. :)

**Comment by martijnat** [comment]
@greduan sure.

**Comment by greduan** [comment]
LGTM

**Comment by jasonm23** [comment]
You can also bump the patch version with any modifications to face definitions.

New mode support should prompt a point release.

If you already know how semver works go ahead and bump the versions yourself.

I use `sed` to do this, e.g.

```
sed -ibak 's/ Version: 0.1.0/ Version: 0.1.1' *.el
```

In the above example assume current version at point 0.1.0, and patching to 0.1.1.

I will merge and bump the version in a subsequent commit after.

**Comment by jasonm23** [comment]
```
bumper() {
    sed -ibak "s+ Version: $1+ Version: $2+" *.el
}
```

**Pull request merged**
